version: '3'
services:
  riemann_branch:
    image: riemann-fw-bug/riemann_branch
    depends_on:
      - riemann_leaf
    build:
      context: .
      dockerfile: Dockerfile-riemann_branch
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 2
  riemann_leaf:
    image: riemann-fw-bug/riemann_leaf
    build:
      context: .
      dockerfile: Dockerfile-riemann_leaf
    networks:
      - backend
      - frontend
    ports:
      - 5555
      - 5556
  collectd_fw:
    image: riemann-fw-bug/collectd_fw
    depends_on:
      - riemann_branch
    build:
      context: .
      dockerfile: Dockerfile-collectd_fw
    networks:
      - backend
  collectd_tg:
    image: riemann-fw-bug/collectd_tg
    depends_on:
      - collectd_fw
    build:
      context: .
      dockerfile: Dockerfile-collectd_tg
    networks:
      - backend
  syslog_ng_loggen:
    image: riemann-fw-bug/syslog_ng_loggen
    depends_on:
      - syslog_ng_fw
    build:
      context: .
      dockerfile: Dockerfile-syslog_ng_loggen
    networks:
      - backend
  syslog_ng_fw:
    image: riemann-fw-bug/syslog_ng_fw
    depends_on:
      - riemann_branch
    build:
      context: .
      dockerfile: Dockerfile-syslog_ng_fw
    networks:
      - backend
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 172.48.0.0/16
