version: '3'
services:
  riemann_branch:
    image: riemann-fw-bug/riemann_branch
    depends_on:
      - riemann_leaf
    build:
      context: .
      dockerfile: Dockerfile-riemann_branch
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 2
  riemann_leaf:
    image: riemann-fw-bug/riemann_leaf
    build:
      context: .
      dockerfile: Dockerfile-riemann_leaf
    networks:
      - backend
      - frontend
    ports:
      - 5555
      - 5556
  collectd_fw:
    image: riemann-fw-bug/collectd_fw
    depends_on:
      - riemann_branch
    build:
      context: .
      dockerfile: Dockerfile-collectd_fw
    networks:
      - backend
  collectd_tg:
    image: riemann-fw-bug/collectd_tg
    depends_on:
      - collectd_fw
    build:
      context: .
      dockerfile: Dockerfile-collectd_tg
    networks:
      - backend
networks:
  backend: ~
  frontend: ~
